### ISSUE TITLE
Are there plans to implement zlib/gzip decompression?

### ISSUE THREAD

**Issue by CandyMi** [wtarreau/libslz#2]
@wtarreau Looking for an alternative to the zlib embed compilation library.

THX.

**Comment by jberryman** [comment]
Not the author, but libdeflate seems to have very fast decompression for gzip

**Comment by wtarreau** [comment]
In fact the main goal of slz is to save memory, which is not really possible when decompressing, so any alternative will be good. I preferred not to deal with that to save users from having to use a possibly inefficient implementation when very good ones already exist. That said, I understand that it's not convenient to have to link with two libraries, and maybe at some point I'll need to either implement one or maybe better, adopt an existing one. If so, that one will need to rely on a compatible license.

**Comment by CandyMi** [comment]
I got it.  : )
